
data:
  max_num_nodes: 125

training:
  batch_size: 32
  learning_rate: 0.0002
  lr_decay: 0.5
  decay_iteration: 1000000
  betas:
    beta1: 0.9
    beta2: 0.999
  epochs: 100_000
  val_size: 40
  #dropout: 0

model:
  architecture: 'gps'
  nhf: 128
  edge_node_ratio: 2
  n_layers: 8
  mlp_n_layers: 3
  normalization: layer_norm
  T: 128
  prior: marginal # 'masking', 'absorbing', 'marginal'
  input_time: True
  predict_all: True

regressor:
  denoiser: False

extra_features:
  spectral_embeddings: True
  k: 5
  graph_size: True
  molecular_feat: False
  cycles: True
  rrwp: False
  rrwp_k: 0

sampling:
  id: 'sid'
  critical: False

log:
  n_loggin_steps: 100
  n_loggin_epochs: 256
  n_test_samples: 117
  n_val_samples: 94
  sampling_batch_size: 117
  n_samples_generation: 117
  save_graphs: False